apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: web-portfolio
  description: personal portfolio website
  annotations:
    github.com/project-slug: joe44824/portfolio
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: development
  lifecycle: experimental

