export const sentences = [
  "Hello and welcome! I'm Zaw Wana, but please feel free to call me Joe",
  "A recent Computing Science graduate from SIT (2025), passionate about modern infrastructure and automation",
  "I specialize in DevOps Engineering with deep expertise in Kubernetes, container orchestration, and cloud-native technologies",
  "Constantly exploring cutting-edge DevOps practices, I enjoy experimenting with new tools and sharing knowledge through technical blogs and community contributions",
  "Currently building out my Homelab infrastructure, where I'm automating workflows with n8n and implementing GitOps practices",
  "I maintain a self-hosted Kubernetes cluster running on a Hypervisor at home - because learning never stops after hours",
  "In fact, this very portfolio is deployed as a pod within my home Kubernetes cluster, demonstrating real-world DevOps in action",
  "Working on showcasing my complete GitOps pipeline using ArgoCD and Terraform for end-to-end automation",
  "When I'm not orchestrating containers, you'll find me contributing to open-source projects or writing about my Homelab experiments",
];

export const expCards = [
  {
    logoPath: "fra.png",
    title: "STEM Educator",
    date: "July 2025 - Present",
    toolImagesPaths: [
      "python.png",
      "raspberrypi.png",
      "scratch.png",
      "embedded.png",
    ],
    toolDescriptions: [
      "Created Python learning modules with real-time coding exercises and automated feedback systems",
      "Built Raspberry Pi projects for environmental monitoring with live sensor data visualization",
      "Developed interactive Scratch games to teach programming fundamentals through visual storytelling",
      "Designed embedded systems projects combining Arduino with sensors for robotics applications",
    ],
    responsibilities: [
      "Designed project-based STEM curriculum",
      "Taught Python fundamentals through interactive games",
      "Guided robotics projects using Arduino",
    ],
    bgColor: "#323332",
  },
  {
    logoPath: "singtel.png",
    title: "DevOps Engineer",
    date: "September 2024 - June 2025",
    toolImagesPaths: [
      "linux.png",
      "ansible.png",
      "kubernetes.png",
      "terraform.png",
      "jenkins.png",
    ],
    toolDescriptions: [
      "Managed Linux server infrastructure and automated system monitoring with custom shell scripts",
      "Implemented Ansible playbooks for consistent configuration management across development environments",
      "Containerized applications with Kubernetes for improved scalability and deployment efficiency",
      "Used Terraform to provision cloud resources and maintain infrastructure as code practices",
      "Maintaining and troubleshooting Jenins Pipelines running on-prem",
    ],
    responsibilities: [
      "Automated infrastructure provisioning using Terraform and standardized Kubernetes deployments with Helm",
      "Maintained and enhanced Jenkins CI/CD pipelines to streamline software delivery and infrastructure automation",
      "Implemented full-stack monitoring with Zabbix for infrastructure, network, and application performance metrics",
      "Troubleshoot and performance-tuned critical data services including OpenSearch, MySQL, Redis, and MongoDB and Containers",
      "Developed Python automation for security (IoC IP filtering) and operational (system health checks) tasks",
      "Managed configuration and daily operations for containerized (Docker) and virtualized environments using Ansible",
    ],
    bgColor: "#f7f7f7",
  },
  {
    logoPath: "urban.png",
    title: "Software Engineer",
    date: "October 2022 - April 2023",
    toolImagesPaths: [
      "flutter.png",
      "nodejs.png",
      "javascript.png",
      "firebase.png",
      "docker.png",
    ],
    toolDescriptions: [
      "Developed Flutter mobile applications with responsive UI designs and smooth animations",
      "Built RESTful APIs with Node.js and Express for data processing and integration",
      "Created interactive data visualizations using JavaScript charting libraries",
      "Implemented Firebase authentication and real-time database solutions",
      "Containerized applications with Docker for consistent deployment across environments",
    ],
    responsibilities: [
      "Engineered a full-stack web solution with a React frontend and Node.js/Express.js backend to create a centralized data aggregation hub for IoT sensors, processing real-time environmental metrics",
      "Designed Intuitive Data Visualization Dashboard: Developed a responsive and user-friendly dashboard using React and Tailwind CSS to visually represent complex sensor data, transforming raw metrics into actionable insights on plant health and environmental conditions",
      "Enabled Data-Driven Decision Making: By providing a single source of truth for sensor data, the dashboard empowered the urban farming team to optimize irrigation, lighting, and climate control, leading to improved crop yield and resource efficiency",
    ],
    bgColor: "#f7f7f7",
  },
  {
    logoPath: "sit.png",
    title: "Software Engineer",
    date: "October 2023 - April 2024",
    toolImagesPaths: [
      "nodejs.png",
      "react.png",
      "javascript.png",
      "docker.png",
    ],
    toolDescriptions: [
      "Developed backend services with Node.js handling data processing and API integrations",
      "Built React applications with state management and responsive component libraries",
      "Implemented client-side logic and data manipulation with modern JavaScript",
      "Created Docker containers for application deployment and environment consistency",
    ],
    responsibilities: [
      "Architected a Scalable Data Management Platform: Engineered a full-stack web dashboard using Flutter for a unified cross-platform UI and Firebase (Firestore, Auth, Functions) for a completely serverless backend, reducing DevOps overhead and infrastructure costs",
      "Delivered Advanced Business Intelligence Features: Implemented critical functionalities including dynamic data visualization charts, automated Excel report generation for stakeholder reviews, and a secure role-based access control (RBAC) system, transforming raw data into actionable insights for the entire team",
      "Optimized Operational Efficiency: The dashboard automated manual data aggregation and reporting processes, saving an estimated 10+ person-hours per week and enabling real-time, data-driven decision-making for key business units",
    ],
    bgColor: "#f7f7f7",
  },
  {
    logoPath: "venture.png",
    title: "Data Analyst",
    date: "April 2019 - July 2019",
    toolImagesPaths: [
      "tableau.png",
      "r_language.png",
      "rapidMiner.png",
      "excel.png",
    ],
    toolDescriptions: [
      "Created Tableau dashboards for data visualization and business intelligence reporting",
      "Performed statistical analysis and data modeling using R programming",
      "Used RapidMiner for predictive analytics and machine learning workflows",
      "Developed Excel models for data analysis, reporting, and process automation",
    ],
    responsibilities: [
      "Developed IoT data collection systems",
      "Performed predictive maintenance analysis",
    ],
    bgColor: "#f7f7f7",
  },
];

export const certificates = [
  {
    id: 1,
    name: "Certified Kubernetes Administrator (CKA)",
    issuer: "Cloud Native Computing Foundation",
    date: "Expected Oct 2025",
    status: "upcoming",
    logo: "🔒",
    color: "from-gray-600 via-gray-700 to-gray-800",
    skills: ["Kubernetes", "Cluster Security", "Troubleshooting"],
    note: "Preparing for exam",
  },
  {
    id: 2,
    name: "AWS Certified Solutions Architect – Associate",
    issuer: "Amazon Web Services",
    date: "Expected Nov 2025",
    status: "upcoming",
    logo: "🔒",
    color: "from-gray-600 via-gray-700 to-gray-800",
    skills: ["AWS Architecture", "High Availability", "Cost Optimization"],
    note: "In progress",
  },
  // Example of an active cert (you can keep or remove)
  // {
  //   id: 3,
  //   name: "AWS Certified Cloud Practitioner",
  //   issuer: "Amazon Web Services",
  //   date: "2023",
  //   status: "active",
  //   credentialId: "AWS-CP-001234",
  //   verifyUrl: "#",
  //   logo: "☁️",
  //   color: "from-orange-400 via-red-500 to-pink-600",
  //   skills: ["AWS", "Cloud Fundamentals", "Cloud Services"],
  // },
];
