apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/joe44824/portfolio.git
    targetRevision: main
    path: k8s/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio-dev
  syncPolicy:
    automated:
      prune: false # Manual sync for production
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
