apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/joe44824/portfolio.git
    targetRevision: dev
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
