apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: portfolio-dev
labels:
  - pairs:
      environment: dev
images:
  - name: joe44824/web-portfolio
    newTag: latest
patches:
  - path: patch.yaml
